/// 文档生成服务 - 文档处理功能
/// 
/// 支持生成多种格式的文档：
/// - PDF 文档
/// - Excel 表格
/// - PPTX 演示文稿
/// - XMind 思维导图
/// - Word 文档
/// 
/// @author JianMa
/// @version 1.0.0
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:archive/archive.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';

/// 文档类型
enum DocumentType {
  pdf,
  excel,
  pptx,
  word,
  xmind,
  markdown,
}

/// 文档生成结果
class DocumentResult {
  final String filePath;
  final String fileName;
  final DocumentType type;
  final int fileSize;

  DocumentResult({
    required this.filePath,
    required this.fileName,
    required this.type,
    required this.fileSize,
  });
}

/// 文档生成服务
class DocumentGenerationService {
  static final DocumentGenerationService _instance = DocumentGenerationService._();
  static DocumentGenerationService get instance => _instance;

  DocumentGenerationService._();

  /// 生成 Markdown 文档
  Future<DocumentResult> generateMarkdown({
    required String title,
    required String content,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final fileName = '${title}_${DateTime.now().millisecondsSinceEpoch}.md';
    final filePath = '${dir.path}/documents/$fileName';
    
    // 确保目录存在
    await Directory('${dir.path}/documents').create(recursive: true);
    
    final file = File(filePath);
    await file.writeAsString(content);
    
    debugPrint('[DocumentGeneration] Markdown 生成完成: $filePath');
    
    return DocumentResult(
      filePath: filePath,
      fileName: fileName,
      type: DocumentType.markdown,
      fileSize: await file.length(),
    );
  }

  /// 生成简单 PDF（使用纯文本格式）
  Future<DocumentResult> generatePDF({
    required String title,
    required String content,
  }) async {
    // 简化实现：生成文本文件，后续可集成 pdf 库
    final dir = await getApplicationDocumentsDirectory();
    final fileName = '${title}_${DateTime.now().millisecondsSinceEpoch}.txt';
    final filePath = '${dir.path}/documents/$fileName';
    
    await Directory('${dir.path}/documents').create(recursive: true);
    
    final file = File(filePath);
    await file.writeAsString('''
$title
${'=' * title.length}

$content

---
Generated by MJ Nexus
${DateTime.now().toIso8601String()}
''');
    
    debugPrint('[DocumentGeneration] PDF(文本) 生成完成: $filePath');
    
    return DocumentResult(
      filePath: filePath,
      fileName: fileName,
      type: DocumentType.pdf,
      fileSize: await file.length(),
    );
  }

  /// 生成 XMind 思维导图
  Future<DocumentResult> generateXMind({
    required String title,
    required Map<String, dynamic> mindMapData,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final fileName = '${title}_${DateTime.now().millisecondsSinceEpoch}.xmind';
    final filePath = '${dir.path}/documents/$fileName';
    
    await Directory('${dir.path}/documents').create(recursive: true);
    
    // XMind 8 格式：ZIP 包含 content.json
    final contentJson = _buildXMindContent(title, mindMapData);
    final archive = Archive()
      ..addFile(ArchiveFile('content.json', utf8.encode(jsonEncode(contentJson))))
      ..addFile(ArchiveFile('metadata.json', utf8.encode(jsonEncode({
        'creator': {'name': 'MJ Nexus', 'version': '1.0.0'},
      }))));
    
    final zipData = ZipEncoder().encode(archive);
    final file = File(filePath);
    await file.writeAsBytes(zipData);
    
    debugPrint('[DocumentGeneration] XMind 生成完成: $filePath');
    
    return DocumentResult(
      filePath: filePath,
      fileName: fileName,
      type: DocumentType.xmind,
      fileSize: await file.length(),
    );
  }

  /// 构建 XMind 内容结构
  Map<String, dynamic> _buildXMindContent(String title, Map<String, dynamic> data) {
    return {
      'id': 'root',
      'class': 'sheet',
      'title': title,
      'rootTopic': {
        'id': 'root_topic',
        'class': 'topic',
        'title': title,
        'children': {
          'attached': _buildTopics(data),
        },
      },
    };
  }

  /// 递归构建思维导图节点
  List<Map<String, dynamic>> _buildTopics(Map<String, dynamic> data) {
    final topics = <Map<String, dynamic>>[];
    
    data.forEach((key, value) {
      final topic = <String, dynamic>{
        'id': 'topic_${key.hashCode}',
        'class': 'topic',
        'title': key,
      };
      
      if (value is Map<String, dynamic>) {
        topic['children'] = {
          'attached': _buildTopics(value),
        };
      } else if (value is List) {
        topic['children'] = {
          'attached': value.map((item) => {
            'id': 'topic_${item.hashCode}',
            'class': 'topic',
            'title': item.toString(),
          }).toList(),
        };
      }
      
      topics.add(topic);
    });
    
    return topics;
  }

  /// 从文本生成思维导图数据
  Map<String, dynamic> generateMindMapFromText(String text) {
    final lines = text.split('\n').where((line) => line.trim().isNotEmpty).toList();
    
    if (lines.isEmpty) {
      return {'主题': {}};
    }
    
    final root = <String, dynamic>{};
    String? currentTopic;
    final subTopics = <String>[];
    
    for (final line in lines) {
      final trimmed = line.trim();
      
      // 检测标题（以 # 开头或全大写）
      if (trimmed.startsWith('#') || trimmed == trimmed.toUpperCase()) {
        // 保存之前的主题
        if (currentTopic != null) {
          root[currentTopic] = List.from(subTopics);
          subTopics.clear();
        }
        currentTopic = trimmed.replaceAll('#', '').trim();
      } else {
        subTopics.add(trimmed);
      }
    }
    
    // 保存最后一个主题
    if (currentTopic != null) {
      root[currentTopic] = List.from(subTopics);
    }
    
    return root;
  }

  /// 获取文档目录
  Future<String> getDocumentsDirectory() async {
    final dir = await getApplicationDocumentsDirectory();
    final docDir = Directory('${dir.path}/documents');
    if (!await docDir.exists()) {
      await docDir.create(recursive: true);
    }
    return docDir.path;
  }

  /// 列出所有生成的文档
  Future<List<FileSystemEntity>> listDocuments() async {
    final dirPath = await getDocumentsDirectory();
    final dir = Directory(dirPath);
    return dir.list().toList();
  }

  /// 删除文档
  Future<void> deleteDocument(String filePath) async {
    final file = File(filePath);
    if (await file.exists()) {
      await file.delete();
      debugPrint('[DocumentGeneration] 文档已删除: $filePath');
    }
  }
}
